### ISSUE TITLE
Test-drive NITELite analysis pipeline

### ISSUE THREAD

**Issue by zhafen** [AdlerFarHorizons/NITELite-pipeline#1]

**Comment by zhafen** [comment]
Basic functionality works. Next up editable configs check, use-case change.

**Comment by hmburd** [comment]
In the description of the pipeline use cases, could we include examples of when you would use the process metadata, create a mosaic, and geoeference images:
(I) process metadata - describe where metadata imported from and how it's transformed, when we do it
(II) create a mosaic - describe where referenced images live, who/how they are referenced for each flight and where the data is imported from
(III) georeference images via a sequential mosaic -describe how the mosaic sequencing model works and where the final mosaic will output/how often will it output? is all this just once per flight?

A) 1) add Link to the aws console sign in https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3FhashArgs%3D%2523%26isauthcode%3Dtrue%26nc2%3Dh_ct%26src%3Dheader-signin%26state%3DhashArgsFromTB_us-east-2_87bbb479361e9ae1&client_id=arn%3Aaws%3Asignin%3A%3A%3Aconsole%2Fcanvas&forceMobileApp=0&code_challenge=AbJaCZd7x3xxKoPX0UQpxffXNhKj2nhkI4oDMuA2fi8&code_challenge_method=SHA-256

A & C) 7) Maybe just add a quick note that we are looking for "Succeeded" Message and what is happening with the container or where the mosaic is or what happens next

B)

**Comment by hmburd** [comment]
![A8EE249F-76CB-44A2-A315-04E142FD87C1](https://github.com/AdlerFarHorizons/NITELite-pipeline/assets/47498136/37e04c4b-dbab-4447-a7ca-e45fed178f00)

B) make sure the user checkouts to another branch before changing the code on the main branch (this could also be done by forking instructions in step 1 maybe?) but just to make sure no one edits the main code permanently with an accidental mistake (except if they are supposed to)

**Comment by zhafen** [comment]
Reopening this to implement changes.

One such change is to note that the configs the user should be updating are in NITELite-pipeline, _not_ night-horizons-mapmaker.

**Comment by zhafen** [comment]
Changes were implemented. New list of changes from the second round:

- Explain why it's called a "build" stage, when we're not building the code.
- Add instructions on accessing the output
- Debug downloading multiple images
- Verify output is a geotiff
- Mention that users don't need to fork every time they make a change
- Change default operation to querying
